name: Linting

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mypy
        pip install -r requirements.txt
        mypy --install-types --non-interactive dsptools
    - name: Run PyLint
      run: |
        pylint $(git ls-files '*.py')

    - name: Run mypy
      run: |
        mypy dsptools
